---

spring:
  main:
    banner-mode: 'off'
  datasource:
    url: 'jdbc:h2:mem:TEST;DB_CLOSE_DELAY=-1;'
    username: 'sa'
    password: ''
    driver-class-name: 'org.h2.Driver'
  jpa:
    hibernate:
      ddl-auto: 'none'
    open-in-view: false

logging:
  level:
    com:
      harcyah: 'DEBUG'
